### ISSUE TITLE
Heat Capacity Analysis

### ISSUE THREAD

**Issue by msinha1** [materialsautomated/materialsautomated.github.io#11] opened 2020-04-04 02:34 UTC
Input: PPMS .dat file containing heat capacity data of a sample.

Output: Cp/T3 vs Log T plot, Cp/T vs Log T fits showing the contributions from each of the phonon modes as well the total fit. A table with the temperature of each of the phonon modes as well as oscillator strengths.

Detailed description: We can approximate the 2D phonon spectra from the Cp/T3 vs T plot where Cp is the heat capacity of a material and T is the temperature. It will be useful to have a tool to identify and plot the graphs and fit the data showing the contribution of Einstein and Debye modes. 

Additionally it will be really helpful if one set of parameters can be obtained by fitting the data in both the plots simultaneously.

Impact: It will reduce the time used for the analysis which is done manually. This fit is extremely useful for the structure and properties correlation of materials.

**Comment by tmcqueen-materials** [comment] 2020-04-04 13:56
Thank you for your suggestion. This is a duplicate of #5. Could you please add your suggestions, including sample inputs and outputs, to that issue? You can include arbitrary file types by placing in a zip archive first.

**Closed as completed by tmcqueen-materials** 2020-04-04 13:56 UTC
